import { parseMotionValue } from "./parse.mjs";

const ATTRIBUTE_TO_ANIMATION = new Map([
  ["vl-effect", { property: "animation-name", timeline: "view" }],
  ["vl-base", { property: "animation-name" }],
  ["vl-enter", { property: "animation-name", timeline: "view", range: "entry 0% cover 40%" }],
  ["vl-exit", { property: "animation-name", timeline: "view", range: "exit 0% exit 100%" }],
  ["vl-scroll", { property: "animation-name", timeline: "view" }],
  ["vl-loop", { property: "animation-name", iteration: "infinite" }],
  ["vl-loop-effect", { property: "animation-name", iteration: "infinite" }],
  ["vl-hover", { property: "--vl-hover-effect" }],
  ["vl-state", { property: "--vl-state-effect" }],
]);

const PRESET_TO_KEYFRAME = new Map([
  ["fade-in", "vl-fade-in"],
  ["fade-out", "vl-fade-out"],
  ["fade-up", "vl-fade-up"],
  ["fade-down", "vl-fade-down"],
  ["fade-out-up", "vl-fade-out-up"],
  ["fade-out-down", "vl-fade-out-down"],
  ["slide-left", "vl-slide-left"],
  ["slide-right", "vl-slide-right"],
  ["scale-in", "vl-scale-in"],
  ["pop-in", "vl-pop-in"],
  ["shrink-out", "vl-shrink-out"],
  ["blur-in", "vl-blur-in"],
  ["3d-entry", "vl-3d-entry"],
  ["flow-in", "vl-flow-in"],
  ["tilt-in", "vl-tilt-in"],
  ["clip-rise", "vl-clip-rise"],
  ["parallax", "vl-parallax-shift"],
  ["scroll-scale", "vl-scroll-scale"],
  ["scroll-horizontal", "vl-scroll-horizontal"],
  ["cinema-zoom", "vl-cinema-zoom"],
  ["shimmer", "vl-shimmer"],
  ["float", "vl-float"],
  ["glow-breathe", "vl-glow-breathe"],
  ["orbit-spin", "vl-orbit-spin"],
  ["rock", "vl-rock"],
  ["spin", "vl-rotate-flat"],
  ["wobble", "vl-tilt-wobble"],
]);

function escapeAttributeValue(value) {
  return value.replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}

function selectorFor(attr) {
  if (!attr.value) return `[${attr.name}]`;
  return `[${attr.name}=\"${escapeAttributeValue(attr.value)}\"]`;
}

function declaration(name, value) {
  return value ? `  ${name}: ${value};` : "";
}

function getFunction(name, parsed) {
  return parsed.functions.find((fn) => fn.name === name);
}

function declarationsForAttribute(attr) {
  if (attr.name === "vl-delay" && attr.value) {
    return [declaration("--vl-motion-delay", attr.value)];
  }

  const contract = ATTRIBUTE_TO_ANIMATION.get(attr.name);
  if (!contract || !attr.value) return [];

  const parsed = parseMotionValue(attr.value);
  const keyframe = PRESET_TO_KEYFRAME.get(parsed.preset);
  if (!keyframe) return [];

  const declarations = [
    declaration(contract.property, keyframe),
    declaration("--vl-motion-duration", parsed.duration),
    declaration("--vl-motion-ease", parsed.ease),
    declaration("animation-duration", "var(--vl-motion-duration, 700ms)"),
    declaration("animation-timing-function", "var(--vl-motion-ease, ease-out)"),
    declaration("animation-fill-mode", "both"),
  ];

  if (contract.timeline) {
    declarations.push(declaration("animation-timeline", "view()"));
  }

  const range = parsed.declarations.range ?? contract.range;
  if (range) {
    declarations.push(declaration("animation-range", range));
  }

  const delay = parsed.declarations.delay;
  if (delay) {
    declarations.push(declaration("animation-delay", delay));
  }

  if (contract.iteration) {
    declarations.push(declaration("animation-iteration-count", contract.iteration));
  }

  const y = getFunction("y", parsed);
  if (parsed.preset === "parallax" && y?.args.length >= 2) {
    declarations.push(declaration("--vl-parallax-from", y.args[0]));
    declarations.push(declaration("--vl-parallax-to", y.args[1]));
  }

  return declarations.filter(Boolean);
}

export function generateCssFromAttributes(attrs) {
  const blocks = [];
  const seen = new Set();

  for (const attr of attrs) {
    const selector = selectorFor(attr);
    const declarations = declarationsForAttribute(attr);
    if (!declarations.length) continue;

    const signature = `${selector}{${declarations.join("")}}`;
    if (seen.has(signature)) continue;
    seen.add(signature);

    blocks.push(`${selector} {\n${declarations.join("\n")}\n}`);
  }

  if (!blocks.length) return "";

  return [
    "@layer velora.motion {",
    "  /* Generated by @velora/compiler. Do not edit by hand. */",
    blocks.map((block) => block.replace(/^/gm, "  ")).join("\n\n"),
    "}",
    "",
  ].join("\n");
}
