export const ALLOWED_VL_ATTRS = new Set([
  "vl-effect",
  "vl-enter",
  "vl-exit",
  "vl-scroll",
  "vl-timeline",
  "vl-range",
  "vl-duration",
  "vl-speed",
  "vl-direction",
  "vl-loop",
  "vl-loop-effect",
  "vl-children",
  "vl-stagger",
  "vl-scene",
  "vl-pin",
  "vl-scrub",
  "vl-once",
  "vl-state",
  "vl-page-transition",
  "vl-vt-shared-nav",
  "vl-vt-shared-brand",
  "vl-logo-lockup",
  "vl-card",
  "vl-actuator",
  "vl-hover",
  "vl-base",
  "vl-scene-trigger",
  "vl-scene-trigger-zone",
  "vl-scale-shift",
  "vl-counter-fwd",
  "vl-scroll-markers",
]);

export const DEPRECATED_VL_ATTRS = new Map([
  ["vl-type", "Use vl-timeline + channel attributes."],
  ["vl-delay", "Use vl-stagger + vl-children."],
  ["vl-easing", "Use easing tokens/effect contracts."],
  ["vl-transition", "Use vl-page-transition + shared View Transition attributes."],
]);

export const CHANNEL_ATTRS = new Set([
  "vl-base",
  "vl-enter",
  "vl-scroll",
  "vl-loop",
  "vl-hover",
  "vl-state",
  "vl-exit",
]);

export const KNOWN_PRESETS = new Set([
  "fade-in",
  "fade-out",
  "fade-up",
  "fade-down",
  "fade-out-up",
  "fade-out-down",
  "slide-left",
  "slide-right",
  "scale-in",
  "pop-in",
  "shrink-out",
  "blur-in",
  "3d-entry",
  "flow-in",
  "tilt-in",
  "clip-rise",
  "parallax",
  "scroll-scale",
  "scroll-horizontal",
  "cinema-zoom",
  "shimmer",
  "float",
  "glow-breathe",
  "wobble",
  "spin",
  "orbit-spin",
  "rock",
  "underline-expand",
  "smooth",
]);

export const VALUE_RULES = {
  "vl-timeline": /^(view|scroll|auto|state|hover)$/,
  "vl-duration": /^(?:\d*\.?\d+m?s|var\(--[a-z0-9-]+\))$/i,
  "vl-stagger": /^(?:\d*\.?\d+m?s|var\(--[a-z0-9-]+\))$/i,
  "vl-speed": /^(slow|normal|fast)$/,
  "vl-direction": /^(normal|reverse|alternate|alternate-reverse)$/,
  "vl-loop": /^(?:-1|infinite|\d+)$/,
};
