export const ALLOWED_VL_ATTRS = new Set([
  "vl-effect",
  "vl-enter",
  "vl-exit",
  "vl-scroll",
  "vl-timeline",
  "vl-range",
  "vl-duration",
  "vl-speed",
  "vl-motion",
  "vl-direction",
  "vl-loop",
  "vl-loop-effect",
  "vl-children",
  "vl-stagger",
  "vl-scene",
  "vl-stage",
  "vl-act",
  "vl-span",
  "vl-pin",
  "vl-scrub",
  "vl-once",
  "vl-state",
  "vl-page-transition",
  "vl-vt-shared-nav",
  "vl-vt-shared-brand",
  "vl-logo-lockup",
  "vl-card",
  "vl-actuator",
  "vl-hover",
  "vl-base",
  "vl-scene-trigger",
  "vl-scene-trigger-zone",
  "vl-scale-shift",
  "vl-counter-fwd",
  "vl-scroll-markers",
]);

export const DEPRECATED_VL_ATTRS = new Map([
  ["vl-type", "Use vl-timeline + channel attributes."],
  ["vl-delay", "Use vl-stagger + vl-children."],
  ["vl-easing", "Use easing tokens/effect contracts."],
  ["vl-transition", "Use vl-page-transition + shared View Transition attributes."],
]);

export const CHANNEL_ATTRS = new Set([
  "vl-base",
  "vl-enter",
  "vl-scroll",
  "vl-loop",
  "vl-hover",
  "vl-state",
  "vl-exit",
]);

export const KNOWN_PRESETS = new Set([
  // Entry / exit
  "fade-in",
  "fade-out",
  "fade-up",
  "fade-down",
  "fade-out-up",
  "fade-out-down",
  "slide-left",
  "slide-right",
  "slide-out-left",
  "slide-out-right",
  "scale-in",
  "pop-in",
  "shrink-out",
  "blur-in",
  "blur-lift",
  "blur-out",
  "3d-entry",
  "reveal-3d",
  "flow-in",
  "tilt-in",
  "clip-rise",
  "clip-drop",
  "glide-in",
  "unfold",
  "flip-in",
  "hinge-down",
  "rise-3d",
  "spring-up",
  "spring-3d",
  "mask-sweep",
  "cinematic-mask",
  "wipe-reveal",
  "img-reveal",
  "text-reveal",
  "text-reveal-up",
  "text-reveal-down",
  "text-line-reveal",
  "text-word-rise",
  "reveal-cinematic",
  "pass-fade",
  "pass-rise",
  // Scroll / parallax
  "parallax",
  "parallax-depth",
  "scroll-scale",
  "scroll-horizontal",
  "scroll-marquee",
  "rotate-scroll",
  "counter-scroll",
  "circle-text-scroll",
  "depth-drift",
  "media-zoom",
  "reveal",
  "crossfade",
  "text-highlight",
  "path",
  // Hover / interactive
  "hover-depth-press",
  "hover-prism",
  "hover-card-stack",
  "hover-card-fan",
  "hover-tilt-3d",
  "hover-depth-stack",
  "hover-glow",
  "hover-lift",
  "hover-spotlight",
  "hover-shell-lift",
  "hover-orb-grid",
  "hover-cross-swap",
  "gradient-sweep",
  "border-trace",
  "border-beam",
  "sweep-border",
  "press",
  "spotlight",
  // Cinematic / depth
  "cinema-zoom",
  "depth-push",
  "depth-enter",
  "levitate-x",
  "drift",
  "orbit",
  // Loop / ambient
  "shimmer",
  "shimmer-text",
  "float",
  "glow-breathe",
  "halo-breathe",
  "breathe",
  "wobble",
  "bounce",
  "spin",
  "spin-slow",
  "orbit-spin",
  "rock",
  "pendulum",
  "aurora",
  "aurora-drift",
  "mesh-pan",
  "pulse-ring",
  "ripple",
  // Text effects
  "typewriter",
  "typewriter-loop",
  "typewriter-soft",
  "underline-expand",
  "gradient-text-color",
  "gradient-slide",
  // Special compositions
  "scene-hero-reveal",
  "scene-feature-flow",
  "scene-story-pin",
  "scene-layer-stack",
  "code-greeting-stack",
  "cube-triad-stage",
  "text-ring-orbit",
  "hover-depth-press",
  "glitch-lite",
  "scanline",
  "duotone",
  "zoom-blur",
  "morph",
  "icon-shift",
  "smooth",
  "enter-exit",
  "expand",
  "top-layer",
  // vl-base intensity presets
  "subtle",
  "balanced",
  "dramatic",
]);

export const VALUE_RULES = {
  "vl-timeline": /^(view|scroll|auto|state|hover)$/,
  "vl-duration": /^(?:\d*\.?\d+m?s|var\(--[a-z0-9-]+\))$/i,
  "vl-stagger": /^(?:\d*\.?\d+m?s|var\(--[a-z0-9-]+\))$/i,
  "vl-speed": /^(slow|normal|fast|cinema|slower|fastest|turbo|ultra-slow)$/,
  "vl-motion": /^(standard|subtle|cinematic|still)$/,
  "vl-direction": /^(normal|reverse|alternate|alternate-reverse)$/,
  "vl-loop": /^(?:-1|infinite|\d+)$/,
};
