/**
 * Tailwind config for the Material Design 3 demo pages in apps/showcase.
 * Used ONLY to compile `showcase-tw-demos.css` — no role in Velora's core framework.
 * The palette mirrors Velora's dark-mode oklch tokens mapped to M3 color roles,
 * for side-by-side comparison demos.
 *
 * `@tailwind base` is intentionally omitted to avoid conflicting with velora.css reset.
 */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./pages/**/*.html"],
  theme: {
    extend: {
      colors: {
        surface: "#0d0f0c",
        background: "#0d0f0c",
        "error-dim": "#ba573f",
        "secondary-container": "#3a3c39",
        "on-secondary": "#1f211e",
        "tertiary-container": "#e2f1c6",
        tertiary: "#f1ffd4",
        primary: "#bbcbb1",
        "on-primary-container": "#c5d5ba",
        "surface-container-highest": "#212720",
        "secondary-fixed": "#e3e3de",
        "on-surface-variant": "#a7ada2",
        "on-tertiary": "#576342",
        "primary-fixed": "#d7e8cc",
        "surface-dim": "#0d0f0c",
        "on-tertiary-container": "#4f5b3a",
        "on-surface": "#e1e7dc",
        "on-primary-fixed": "#35432f",
        "surface-container": "#171b16",
        "on-primary-fixed-variant": "#51604a",
        "surface-bright": "#272e25",
        "outline-variant": "#434a41",
        "surface-container-lowest": "#000000",
        "on-tertiary-fixed": "#3e4a2b",
        "on-error-container": "#ff9b82",
        "surface-container-low": "#111410",
        "inverse-primary": "#55634d",
        "inverse-surface": "#fafaf4",
        "on-secondary-fixed-variant": "#5a5c58",
        "surface-container-high": "#1c211b",
        "on-primary": "#364430",
        "secondary-dim": "#9d9e9a",
        "on-secondary-container": "#bfc0bb",
        "on-tertiary-fixed-variant": "#5a6745",
        "tertiary-fixed": "#e5f4c9",
        "surface-variant": "#212720",
        "primary-container": "#3d4b36",
        "on-background": "#e1e7dc",
        "surface-tint": "#bbcbb1",
        "primary-fixed-dim": "#c9d9be",
        "tertiary-dim": "#d7e5bb",
        "primary-dim": "#aebea4",
        "secondary-fixed-dim": "#d4d5d0",
        error: "#ed7f64",
        secondary: "#9d9e9a",
        "tertiary-fixed-dim": "#d7e5bb",
        "on-secondary-fixed": "#3e403d",
        outline: "#71776e",
        "on-error": "#450900",
        "error-container": "#7e2b17",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "system-ui", "sans-serif"],
        body: ["Manrope", "system-ui", "sans-serif"],
        label: ["Manrope", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
